// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlatData;

#nullable disable

namespace PlatData.Migrations
{
    [DbContext(typeof(DbTContext))]
    [Migration("20220106090441_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PlatData.SysTable.SysAdmin", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(0);

                    b.Property<string>("Avatar")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(100);

                    b.Property<bool>("GcRecord")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDisable")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(99)
                        .HasComment("上次更新时间");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NickName")
                        .HasColumnType("longtext");

                    b.Property<string>("ParentId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasComment("随机key密码加密使用");

                    b.Property<string>("Sex")
                        .HasColumnType("longtext");

                    b.Property<string>("SysAdminLogfk")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("SysAdmin");

                    b.HasComment("系统管理员");
                });

            modelBuilder.Entity("PlatData.SysTable.SysAdminGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(100);

                    b.Property<bool>("GcRecord")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDisable")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(99)
                        .HasComment("上次更新时间");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SysAdminGroup");
                });

            modelBuilder.Entity("PlatData.SysTable.SysAdminLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(0);

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Controller")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ControllerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(100);

                    b.Property<bool>("GcRecord")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(99)
                        .HasComment("上次更新时间");

                    b.Property<string>("Param")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ParentFk")
                        .HasColumnType("varchar(255)")
                        .HasComment("管理员关联外键");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ParentFk");

                    b.ToTable("SysAdminLog");
                });

            modelBuilder.Entity("PlatData.SysTable.SysAdminMenu", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(100);

                    b.Property<bool>("GcRecord")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(99)
                        .HasComment("上次更新时间");

                    b.Property<string>("SysAdminKey")
                        .HasColumnType("varchar(255)")
                        .HasComment("关联外键");

                    b.HasKey("Id");

                    b.HasIndex("SysAdminKey")
                        .IsUnique();

                    b.ToTable("SysAdminMenu");
                });

            modelBuilder.Entity("PlatData.SysTable.SysEducation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(100);

                    b.Property<bool>("GcRecord")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(99)
                        .HasComment("上次更新时间");

                    b.Property<DateTime>("LastUpdatedShadow")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastUpdateded")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("SysEducation");

                    b.HasComment("EF教学表");
                });

            modelBuilder.Entity("PlatData.SysTable.SysMenu", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(100);

                    b.Property<bool>("GcRecord")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Icon")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnOrder(99)
                        .HasComment("上次更新时间");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ParentId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<string>("SysAdminMenuId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("isDel")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("SysAdminMenuId");

                    b.ToTable("SysMenu");
                });

            modelBuilder.Entity("PlatData.SysTable.SysAdmin", b =>
                {
                    b.HasOne("PlatData.SysTable.SysAdminGroup", "Parent")
                        .WithMany("SysAdminList")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("PlatData.SysTable.SysAdminLog", b =>
                {
                    b.HasOne("PlatData.SysTable.SysAdmin", "Parent")
                        .WithMany("SysAdminLog")
                        .HasForeignKey("ParentFk")
                        .HasPrincipalKey("SysAdminLogfk")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("PlatData.SysTable.SysAdminMenu", b =>
                {
                    b.HasOne("PlatData.SysTable.SysAdminGroup", "ByGroup")
                        .WithOne("MenuList")
                        .HasForeignKey("PlatData.SysTable.SysAdminMenu", "SysAdminKey");

                    b.Navigation("ByGroup");
                });

            modelBuilder.Entity("PlatData.SysTable.SysMenu", b =>
                {
                    b.HasOne("PlatData.SysTable.SysMenu", "Parent")
                        .WithMany("ChildrenList")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlatData.SysTable.SysAdminMenu", null)
                        .WithMany("Menus")
                        .HasForeignKey("SysAdminMenuId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("PlatData.SysTable.SysAdmin", b =>
                {
                    b.Navigation("SysAdminLog");
                });

            modelBuilder.Entity("PlatData.SysTable.SysAdminGroup", b =>
                {
                    b.Navigation("MenuList")
                        .IsRequired();

                    b.Navigation("SysAdminList");
                });

            modelBuilder.Entity("PlatData.SysTable.SysAdminMenu", b =>
                {
                    b.Navigation("Menus");
                });

            modelBuilder.Entity("PlatData.SysTable.SysMenu", b =>
                {
                    b.Navigation("ChildrenList");
                });
#pragma warning restore 612, 618
        }
    }
}
